[package]
name = "ifloxiei/ratelimiter"
version = "3.2.0"
description = "Hardened, zero-allocation O(1) RateLimiter engine for Roblox."
authors = ["IFloXieI <https://github.com/Jeremy84100>"]
license = "MIT"
realm = "server"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
