[package]
name = "jeremy84100/ratelimiter"
version = "3.2.7"
description = "Hardened, zero-allocation O(1) RateLimiter engine for Roblox."
authors = ["IFloXieI <https://github.com/Jeremy84100>"]
license = "MIT"
realm = "server"
registry = "https://github.com/UpliftGames/wally-index"

# On pointe vers le src/ proprement
main = "src/init.lua"

# On exclut ce qui n'est pas du code source
exclude = [
    "src/shared/**",
    "src/server/**",
    "src/client/**",
    ".agents/**",
    ".gemini/**",
    "skills-lock.json",
    "default.project.json",
    "aftman.toml",
    "*.lock",
    ".github/**",
    "tests/**",
    "StressTest.server.lua"
]

[dependencies]
